name: Deploy to production
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    env:
      REDIS_URI: redis://localhost:6379
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: setup nodejs
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: install dependencies
        run: npm ci

      - name: testing
        run: npm test

      - name: build
        run: npm run build
